### ISSUE TITLE
Thu thập - Hỗ trợ lựa chọn bản đồ nền

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/gserver#1]
Hỗ trợ lựa chọn bản đồ nền ngay trên giao diện khai thác bản đồ --> không phải vào quản trị.

**Comment by vietlv** [comment]
Đã cập nhật chức năng chọn bản đồ nền trên giao diện khai thác bản đồ

**Comment by nguyendangcuong** [comment]
Hiện nay giao diện chọn bản đồ rất khó chọn trên một số máy. Thử nghiệm trên máy asus của công ty để đánh giá.

**Comment by vietlv** [comment]
Đã fix
