### ISSUE TITLE
Thu thập - Bản đồ nền

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/gserver#10]
Hiện tại bản đồ nền khi chuyển đổi vẫn giữ các bản đồ nền cũ(hình như chưa xóa đi) và bổ sung thêm bản đồ nền mới. Khi xem thì thấy hiển thị rất nhiều bản đồ nền lần lượt phủ lên nhau.

**Comment by vudq** [comment]
Thông tin chưa rõ:
- Cái này trên mobile?
- Đổi bản đồ nền là đổi nên thật hay bản đồ offline
Trong citywork(mobiwork) bản đồ offline không phải là nền mà là lớp overlay, còn nội dung của nó lúc thì nền lúc thì chuyên đề phủ lên một nền hoặc một bản đồ offline khác

**Comment by nguyendangcuong** [comment]
Cái này trên mobile, Trên giao diện đã uncheck hết "Lớp bản đồ" + "Bản đồ nền->không dùng" -> nhưng vẫn thấy có bản đồ.

**Comment by vietlv** [comment]
Đã fix lỗi nhiều lớp phủ lên nhau
