### ISSUE TITLE
Thu thập - Thêm mới một đối tượng hoặc sửa...

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/gserver#11]
- Bấm vào định vị thì pan đến vị trí GPS và hiển thị mức zoom lớn nhất? --> Trao đổi để thống nhất sao cho thuận tiện
- Không có các đối tượng đã thu thập trên lớp đang thu thập để phục vụ tham chiếu --> Sẽ khó định vị đối tượng mới.

**Comment by vudq** [comment]
Vấn đề 2: NPC có tính năng này, kiểm tra xem đã tích hợp vào phiên bản hiện tại chưa

**Comment by duongnv1989** [comment]
Thống nhất: L

**Comment by vietlv** [comment]
Đã sửa trên bản mobile, cho phép hiển thị tối đa 10 đối tượng gần nhất(theo khoảng cách) đối tượng chỉnh sửa hoặc thêm mới. Bản cập nhật sẽ có trên store vào chiều nay 10/11
