### ISSUE TITLE
Công việc - Cấu hình mở rộng - Giá trị chọn nhiều

### ISSUE THREAD

**Issue by thoathoa91** [duongnv1989/gserver#13]
Điều chỉnh lại hiện thị Chọn nhiều. Hiện tại sổ giá trị ra rất ko chọn được
Kích vào sổ giá trị xuống và có ô vuông để người dùng tich chọn

![chonnhiu](https://cloud.githubusercontent.com/assets/12489133/10932624/bfea40ba-8304-11e5-8214-3e055d8d7147.jpg)
![chonnhieukhac](https://cloud.githubusercontent.com/assets/12489133/10932625/bff282f2-8304-11e5-8679-a3f6bacf4d20.jpg)

**Comment by vietlv** [comment]
Đã fix lỗi hiển thị
