### ISSUE TITLE
Thu thập - Đồng bộ dữ liệu

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/gserver#14]
1. Sau khi đi thu thập --> Đồng bộ dữ liệu từ mobile --> Biểu mẫu.
2. Dữ liệu từ biểu mẫu --> Đồng bộ vào gServer.
3. Cập nhật lại dữ liệu trên gServer (sửa nội dung, kết quả thu thập).
4. Sang biểu mẫu --> Đồng bộ (Dữ liệu trên biểu mẫu không thay đổi theo dữ liệu đã cập nhật trên gServer)
5. Dữ liệu bên gServer bị cập nhật lại về dữ liệu bên thu thập.

- Cần thống nhất cơ chế cập nhật, đồng bộ dữ liệu
- Dữ liệu đồng bộ từ biểu mẫu -> gServer thì bản đồ cũng chưa hiển thị ngay, người dùng phải xóa cache lớp dữ liệu đi mới hiện thị.

**Comment by duongnv1989** [comment]
- Hiện tại có hai chiều đồng bộ:
      + Nếu đồng bộ từ collector sang gServer: Luôn luôn ưu tiên theo chiều từ biểu mẫu sang lớp dữ liệu (nếu thông tin đối tượng bên gServer mà thay đổi thì nó sẽ được cập nhật lại từ biểu mẫu)
      + Nếu đồng bộ từ gServer sang collector: Luôn luôn ưu tiên theo chiều từ gServer sang collector
Vì vây: Cần tùy thuộc vào thông tin dữ liệu được cập nhật theo chiều nào để dùng chức năng cho đúng ngữ cảnh
- Lỗi xóa cache đã được cập nhật

**Comment by votahuy** [comment]
Sao a vẫn chưa thấy hiển thị 10 điểm gần nhất

Vào Thứ Ba, ngày 10 tháng 11 năm 2015, duongnv1989 <notifications@github.com>
đã viết:

**Comment by vietlv** [comment]
Anh cần vào store để tải bản cập nhật mới nhất mới có chức năng này.
Phần mềm không tự động cập nhật được.
