### ISSUE TITLE
Công việc - Tài khoản 'admin'

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/gserver#15]
- Trong phân hệ công việc: Người giao việc -> không hiện thị tài khoản admin ra. Vì toàn bộ hệ thống đang ẩn tài khoản này? chỉ có vào phần công việc là nhìn thấy tài khoản này.

- Hiển thị thông tin tài khoản cần hiện thị đầy đủ để biết tên người dùng.
![image](https://cloud.githubusercontent.com/assets/8967627/10963368/767dcaae-83d2-11e5-9289-c535e44531c5.png)
Nếu tên dài đang không hiển thị hết (..Nguyễn Ngọc Thắng)

**Comment by vietlv** [comment]
- Đã không hiển thị tài khoản admin.
- Bổ xung hiển thị title của người dùng bao gồm cả tên và email để dễ xác định tài khoản, tự thêm dấu 3 chấm khi tên dài quá mức hiển thị
