### ISSUE TITLE
Reportviewer - Hiển thị control datetime trong báo cáo trên chrome

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/gserver#16]
- Hiện tại khi xem báo cáo có tham số kiểu datetime thì trên chrome không hiển thị.
FF và IE okie.
![image](https://cloud.githubusercontent.com/assets/8967627/10963835/cc7d11dc-83d5-11e5-9e04-6321afe65c6c.png)
![image](https://cloud.githubusercontent.com/assets/8967627/10963845/e7f8f570-83d5-11e5-8306-440852d22c99.png)

- Báo cáo mẫu: tổ chức chiếu sáng --> Chọn báo cáo "Kết quả kiểm tra mạng lưới"
- Tham khảo fix lỗi: 
http://www.rajbandi.net/fixing-ssrs-report-viewer-control-date-picker-in-google-chrome/
http://www.codeproject.com/Articles/504567/Print-button-Date-picker-in-SSRS-Reports-for-Non-I

**Comment by nguyendangcuong** [comment]
Xem báo cáo:
- http://app.citywork.vn/greport1.aspx?itemID=7DBE30C8-7ED4-4B93-83FC-4F521ED81D40 có hiện ra control datetime -> sau khi bấm xem một lần lại mất đi
- http://app.citywork.vn/greport1.aspx?itemID=7DBE30C8-7ED4-4B93-83FC-4F521ED81D40
Không phải là control combobox lại hiện datetime bên cạnh
- http://app.citywork.vn/greport1.aspx?itemID=7DBE30C8-7ED4-4B93-83FC-4F521ED81D40
không phải là trường datetime nhưng vẫn hiện control bên cạnh

**Comment by duongnv1989** [comment]
@chinhls : Kiểm tra khi click button Xem báo cáo (bên phải phía trên) thì control datetime vẫn lỗi, bị mất đi (chỉ lỗi trên chrome)

**Comment by vudq** [comment]
Hạn chế đưa các link của hệ thông mình cũng như các vấn đề về bảo mật lên đây
