### ISSUE TITLE
Thu thập - Biểu mẫu đã xóa

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/gserver#17]
- Mobile thực hiện đồng bộ giả sử ban đầu có 02 biểu mẫu.
- Khi quản trị xóa một biểu mẫu, trên mobile thực hiện đồng bộ nhưng vẫn thấy 02 biểu mẫu vẫn có biể mẫu đã xóa.(Chỉ có xóa cache đi đồng bộ lại mới mất)
- Người dùng nếu vẫn thu thập thì vẫn thu thập và đồng bộ dữ liệu bình thường với biểu mẫu đã bị xóa. Trên web vẫn ghi lại nhật ký hoạt động trên biểu mẫu đó
- Đề xuất khi quản trị xóa biểu mẫu đi thì khi mobile đồng bộ cũng sẽ không nhìn thấy biểu mẫu đó.

**Comment by vietlv** [comment]
- Khi người dùng xóa biểu mẫu trên web, người dùng mobile chưa thực hiện việc đồng bộ thì tất nhiên vẫn còn thấy được biểu mẫu
- Sau khi thực hiện thao tác đồng bộ thì biểu mẫu nào đã được xóa trong quản trị thì sẽ không còn thấy trên mobile.
