### ISSUE TITLE
Thu thập - Tab hoạt động

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/gserver#2]
Tab hoạt động lỗi font chữ.  --> Bên tổ chức chiếu sáng cs0000
![image](https://cloud.githubusercontent.com/assets/8967627/10837128/6f785ede-7ee8-11e5-9fb1-e64439806d2e.png)

**Comment by vietlv** [comment]
Thông tin "null" là các bản ghi được nhập dữ liệu từ gserver sang gcollector, hiện đã được chỉnh sửa thành "Lớp dữ liệu"
Lỗi font hiện chưa gặp lại -> khó phát hiện để khắc phục
