### ISSUE TITLE
Thu thập - nhập số liệu trên máy asus

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/gserver#20]
Với một số máy như asus --> kích thước bàn phím nhập liệu hơi cao do đó sẽ che mất dòng cuối cùng trên biểu mẫu nhập liệu --> dẫn đến không nhập được liệu cho dòng cuối cùng này.
![image](https://cloud.githubusercontent.com/assets/8967627/11162542/c7a5947c-8ad8-11e5-890d-8f1ed197c6c7.png)
Trong hình là bàn phím che mất dòng Ghi chú

**Comment by vietlv** [comment]
Lỗi này do màn hình có bàn phím quá cao so với mức bình thường, cần tính toán lại độ cao cho phù hợp
