### ISSUE TITLE
Citywork - Bản đồ nền

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/gserver#21]
Hiện tại bản đồ nền trên các ứng dụng:
gserver, gcollector, mobile chưa thống nhất một bộ quy chuẩn chung: tên chưa thống nhất, thứ tự trong danh sách chưa thống nhất, mức zoom chưa thống nhất. Cần tham khảo bên gServer để thống nhất trên các ứng dụng khác. Mức zoom bản đồ ở các ứng dụng cần đạt mức 20.

**Comment by vietlv** [comment]
+ Để hiển thị tương quan trên thu thập được rõ hơn e đã chỉnh cho phép zoom tới level 22(trong khi mức zoom tối đa thực tế là 18) riêng đối với bản đồ google mức zoom tối đa thực tế là tới 20 
+ Phiên bản trên mobile cũng sẽ được chỉnh lại level zoom tương tự trên web để có thể nhìn tối đa hơn
