### ISSUE TITLE
Thu thập - Trường dự án

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/gserver#24]
Hiện tại trường dự án đang chưa được đưa vào sử dụng, do vậy cần có cấu hình sử dụng, hay ko sử dụng (nếu sử dụng thì mới hiển thị trên giao diện trên web cũng như mobile - mặc định thì không sử dụng như trường "trạng thái") vì hiện tại chưa có kịch bản sử dụng trường này.

**Comment by vietlv** [comment]
+ Đã chỉnh sửa: Nếu không có dự án nào thì ẩn trường dự án trong giao diện chi tiết bản ghi
