### ISSUE TITLE
gEditor - Bản đồ địa danh google làm lớp chuyên đề

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/gserver#26]
Khi thêm bản đồ địa danh google làm lớp chuyên đề. Để mức hiện thị từ level10 - level14.
Khi zoom đến level chi tiết vd level18 nếu click vào cho hiển thị lớp chuyên đề, thì không hiển thị bản đồ địa danh đúng level mà là bản đồ địa danh của level14.
Xem bản đồ bên hệ thống cấp nước để kiểm tra.

**Comment by duongnv1989** [comment]
@chinhls : bỏ cơ chế client zoom khi không phải lớp bản đồ nền

**Comment by duongnv1989** [comment]
@chinhls : kiểm tra với bản đồ có mức xem nhỏ nhất > 0 thì zoom bản đồ sai
