### ISSUE TITLE
Đồng bộ trên mobile

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/gserver#27]
Khi gọi chức năng đồng bộ. Thực hiện đồng bộ mọi biểu mẫu (Đã okie). Trong giao diện biểu mẫu Thu thập --> khi gọi đồng bộ --> Thực hiện đồng bộ (okie) và chỉ được hiển thị các biểu mẫu của loại Thu thập, tương tự các loại khác. Hiện tại khi gọi đồng bộ xong - là hiển thị tất cả các biểu mẫu ra (Không phân biệt trong ứng dụng nào).

**Comment by vietlv** [comment]
Khi chọn ứng dụng tự động lưu lại để khi đồng bộ sẽ hiển thị đúng danh sách các biểu mẫu tương ứng. Ứng dụng sẽ được cập nhật vào sáng nay ngày 23/11
