### ISSUE TITLE
Mobile - Công việc

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/gserver#31]
- Tải danh sách công việc hơi chậm (Cần cải tiến).
- Khi vào công việc -> Cần hiển thị loading để người dùng biết đang tải dữ liệu (Khi tải xong thì ẩn đi).
Hiện tại không có thông báo gì, khi mạng chậm mãi mới ra danh sách công việc. Nếu không hiện loading -> Người dùng tưởng tải xong rồi -> Ko có công việc nào cần làm.
- Bố trí thông tin tổng số công việc trên giao diện (để người dùng biết có bao nhiêu công việc)

**Comment by vietlv** [comment]
1. Đã có loading khi vào mục công việc
2. Bình thường 1 người sẽ không thực hiện quá nhiều công việc 1 lúc do đó việc hiển thị số lượng công việc là không cần thiết
