### ISSUE TITLE
Mobile - Xem thông tin công việc

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/gserver#34]
- Khi xem thông tin công việc trên mobile -> không xem được bản ghi đính kèm với công việc đó
- Trong công việc, loại công việc có thiết kế biểu mẫu mở rộng - nếu biểu mẫu có trường hình ảnh. Khi lưu trữ hình ảnh trong công việc không được.

**Comment by vietlv** [comment]
Đã sửa xong và cập nhật lên store
