### ISSUE TITLE
gEditor - Tìm kiếm

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/gserver#5]
Trường tìm kiếm là danh mục: hỗ trợ gõ vào để tìm đến đối tượng cần chọn
VD: nếu danh sách Tủ điện nhiều thì khó tìm được tủ điện cần chọn để tìm kiếm
![image](https://cloud.githubusercontent.com/assets/8967627/10837770/e22e3c9e-7eef-11e5-9b5a-b4404b069fc8.png)

**Comment by duongnv1989** [comment]
Hiện tại chỉ lọc được theo trang hiện tại, combo đang để chế độ phân trang (nếu nhiều trang thì cần next trang để lọc)
