### ISSUE TITLE
Thu thập - Đồng bộ dữ liệu

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/gserver#8]
- Sau khi đi thu thập, về đồng bộ dữ liệu --> Người dùng không xem được ảnh các bản ghi mình đi thu thập. Nhưng lại có thể xem ảnh của các bản ghi người khác thu thập trên mobile.
- Có một số máy đã đồng bộ về rồi nhưng không xóa ảnh trong máy đi --> Máy GiangTT.
- Đồng bộ hết rồi - ảnh đưa lên được rồi --> nhưng trên mobile vẫn hiện thị chưa đồng bộ hết ảnh --> Máy GiangTT

**Comment by vietlv** [comment]
Bản hiện tại đang sử dụng cơ chế sau khi đồng bộ dữ liệu thành công thì xóa hết hình ảnh, video trong máy đó đi để tiết kiệm dung lượng.
Khi người khác đồng bộ về thì nhìn thấy ảnh vì đó là ảnh có đường dẫn từ gserver.

**Comment by vietlv** [comment]
Đã fix lỗi, nếu ảnh đã đồng bộ sẽ tính lại đường dẫn của server để view ảnh, lúc này muốn xem được ảnh thì cần có mạng để xem vì link xem là online
