### ISSUE TITLE
Thu thập - Nhập dữ liệu

### ISSUE THREAD

**Issue by nguyendangcuong** [duongnv1989/gserver#9]
- Khi sửa một bản ghi, hoặc khi thêm mới nhập một số thông tin rồi --> nhưng nếu back lại thì không hỏi gì --> do đó mất dữ liệu đã nhập.    
- Bản bên mobiwork có xử lý tốt phần này. (Sửa, thêm mới, hoặc mở ra không làm gì thì đã xử lý hợp lý)

**Comment by vietlv** [comment]
Lỗi này e đã kiểm tra và bên mobiwork cũng có lỗi. Lúc trước bên đó làm cho bên ghi chỉ số chỉ kiểm tra thay đổi của số chứ không kiểm tra text.
Em đã fix và báo lỗi lại cho bên mobiwork.

Bản cập nhật sẽ có trong cuối tuần trên store
